adv_board/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from landing import views
from registration.backends.hmac.views import RegistrationView
from users.forms import UnikoRegistrationForm
from users.views import UnikoRegistrationView
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r"^$", views.Homepage.as_view(), name="landing"),
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include("advert_messages.urls")),
    url(r'^users/', include("users.urls")),
    url(r'^board/', include("board.urls")),
    url(r'^accounts/register/$', UnikoRegistrationView.as_view(form_class=UnikoRegistrationForm),
        name='registration:registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls', namespace="registration")),
    url(r'^users/profiles', views.Homepage.as_view(), name="registration_complete"),
    url(r'^users/profiles', views.Homepage.as_view(), name="registration_activation_complete"),
    url(r'^privacy_policy$', TemplateView.as_view(template_name='privacy_policy.html'), name='privacy_policy'),
    url(r'^terms_of_service$', TemplateView.as_view(template_name='terms_of_service.html'), name='terms'),
    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^faq$', TemplateView.as_view(template_name='faq.html'), name='faq'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
# from .views import AdvertViewSet, StakesViewSet
# from rest_framework.routers import DefaultRouter
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.AdvertListView.as_view(), name="advert-list"),
    url(r'^([0-9]+)/$', views.AdvertListView.as_view(), name="advert-list-cats"),
    url(r'^add_advert/$', views.AdvertCreate.as_view(), name="add-advert"),
    url(r'^edit_advert/(?P<pk>[0-9]+)/$',
        views.AdvertUpdate.as_view(), name="edit-advert"),
    url(r'^del_advert/(?P<pk>[0-9]+)/$',
        views.AdvertDelete.as_view(), name="delete-advert"),
    url(r'^advert/(?P<pk>[0-9]+)/$',
        views.AdvertDetail.as_view(), name="advert-detail"),
    url(r"^advert/(?P<pk>[0-9]+)/check_sold/$",
        views.AdvertSoldView.as_view(), name="advert_check_sold"),
    url(r"^advert/(?P<pk>[0-9]+)/sold", views.AdvertSoldUpdate.as_view(), name="advert_sold"),
]


# router = DefaultRouter()
# router.register(r'advert', AdvertViewSet)
# router.register(r'stakes', StakesViewSet)

# urlpatterns = router.urls

board/models.py
from django.db import models
from users.models import UserProfile
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(_("Category"), max_length=100)
    pictogram = models.CharField(_("Pict"), max_length=50, blank=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name


class AdvertManager(models.Manager):
    def get_queryset(self):
        return super(AdvertManager, self).get_queryset()

    def on_sale(self):
        return super(AdvertManager, self).get_queryset().filter(sold=False, hidden=False)


class Advert(models.Model):

    CONDITIONS = (("used", "Used"), ("like_new", "Like new"), ("new", "New"))

    owner = models.ForeignKey(UserProfile, verbose_name=_("Seller"))
    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(_("Description"))
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(
        _("Price"), max_digits=10, decimal_places=2, default=0)
    item_condition = models.CharField(
        _("Condition"), max_length=8, choices=CONDITIONS, blank=True, null=True)
    sold = models.BooleanField(_("Sold"), default=False)
    sold_to = models.ForeignKey(UserProfile, verbose_name=_(
        "Buyer"), related_name=_("Buyer"), null=True, blank=True)
    hidden = models.BooleanField(_("Hide"), default=False)
    category = models.ForeignKey(Category)

    objects = AdvertManager()

    class Meta:
        verbose_name = _("Advert")
        verbose_name_plural = _("Adverts")
        ordering = ["created_at"]

    def get_absolute_url(self):
        return reverse('advert-detail', kwargs={'pk': self.id})

    @property
    def main_image(self):
        img = AdvertImages.objects.filter(advert=self).first()
        if img:
            return img.image.url
        else:
            return ""  # static No-image-placeholder

    def __str__(self):
        return "{}".format(self.title)


class AdvertImages(models.Model):
    advert = models.ForeignKey(Advert)
    image = models.ImageField(upload_to='adverts')

board/forms.py
from django.forms import ModelForm, inlineformset_factory
from .models import Advert, AdvertImages


class AdvertForm(ModelForm):
    class Meta:
        model = Advert
        fields = ("title", "description", "price", "item_condition", "hidden", "category")


class AdvertImagesForm(ModelForm):
    class Meta:
        model = AdvertImages
        fields = "__all__"

ImageFormset = inlineformset_factory(
    Advert, AdvertImages, fields=("image",), extra=1)

board/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from .models import Advert, AdvertImages, Category
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import AdvertForm, ImageFormset
from django.contrib.auth.mixins import LoginRequiredMixin
from .serializers import AdvertSerializer, FullAdvertSerial
from rest_framework import generics, status
from django.views.generic.detail import DetailView
from rest_framework.response import Response
from advert_messages.models import Message
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.db.models import Q


class AdvertListView(LoginRequiredMixin, ListView):
    model = Advert
    template_name = "board/index.html"

    def get_queryset(self, **kwargs):
        get_query = self.request.GET.get("search_query")

        try:
            category_id = self.args[0]
        except Exception as e:
            category_id = None
        if category_id:
            queryset = Advert.objects.on_sale().filter(
                owner__campus=self.request.user.profile.campus, category__id=category_id)
        else:
            queryset = Advert.objects.on_sale().filter(
                owner__campus=self.request.user.profile.campus)

        if get_query:
            queryset = queryset.filter(Q(title__icontains=get_query) | Q(
                description__icontains=get_query))

        return queryset

    def get_context_data(self):
        context = super(AdvertListView, self).get_context_data()
        context["categories"] = Category.objects.all()
        return context


class AdvertCreate(CreateView):
    model = Advert
    form_class = AdvertForm
    success_url = reverse_lazy('advert-list')

    def form_valid(self, form):
        form.instance.owner = self.request.user.profile
        self.object = form.save()
        files = self.request.FILES.getlist('files[]')
        for file in files:
            image_obj = AdvertImages(advert=self.object)
            image_obj.image.save(file.name, file)
            image_obj.save()
        return redirect('advert-detail', self.object.pk)


class AdvertUpdate(UpdateView):
    model = Advert
    form_class = AdvertForm
    template_name = "board/advert_update.html"

    def get_success_url(self, **kwargs):
        view_name = 'advert-detail'
        return reverse(view_name, kwargs={'pk': self.object.id})

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user.profile

        instance.save()
        form.save_m2m()

        files = self.request.FILES.getlist('files[]')
        for file in files:
            image_obj = AdvertImages(advert=self.object)
            image_obj.image.save(file.name, file)
            image_obj.save()

        return redirect('advert-detail', self.object.pk)


class AdvertDelete(DeleteView):
    model = Advert
    success_url = reverse_lazy('/')


class AdvertDetail(DetailView):
    model = Advert
    fields = "__all__"

    def get_context_data(self, **kwargs):
        obj = kwargs.get("object")
        context = super(AdvertDetail, self).get_context_data(**kwargs)
        context['images'] = AdvertImages.objects.filter(advert=obj)
        return context


class AdvertSoldView(generics.RetrieveAPIView):
    model = Advert
    serializer_class = AdvertSerializer
    queryset = Advert.objects.all()


class AdvertSoldUpdate(generics.UpdateAPIView):
    model = Advert
    serializer_class = FullAdvertSerial
    queryset = Advert.objects.all()

    def update(self, request, *args, **kwargs):
        obj = get_object_or_404(Advert, pk=kwargs["pk"])
        if obj is None:
            return Response(status=status.HTTP_404_NOT_FOUND)
        # obj.sold = True
        # obj.sold_to = UserProfile.objects.all().first()
        obj.save()
        Message.objects.create(
            user=self.owner, author=self.sold_to, message_text="Sold", advert=self.id)
        return Response("201")

templates/board/advert_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="ad-info">
	<div class="ad-images">
		<!-- <ul>
			{% for image in images %}
			<li><img class = "product-image" src="{{image.image.url}}" alt="product-image"></li>
			{% endfor %}
		</ul> -->
		<!-- bootstrap carousel -->
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="false">
      {% for image in images %}
			  <!-- Indicators -->
			  <!-- <ol class="carousel-indicators">
			    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
			  </ol> -->
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			    <div class="item active srle">
			      <img src="{{image.image.url}}" alt="1.jpg" class="img-responsive">
			    </div>
			  </div>
			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			    <span class="fa fa-chevron-left"></span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			    <span class="fa fa-chevron-right"></span>
			  </a>

			  <!-- Thumbnails -->
			  <ul class="thumbnails-carousel clearfix">
			  	<li><img src="{{ image.image.url }}" alt=""></li>
			  </ul>

			  {% endfor %}
			</div>
	</div>
	<div class="ad-desc">
		<div class="ad-owner">
			<a href="{% url 'user_profile' object.owner.id %}"><img src="{{object.owner.avatar_url }}" class = "owner-photo"alt=""></a><span>{{object.owner}}</span>
		</div>
		<hr>
		<div class="ad-title">
			{{object.title}}
		</div>
		<div class="ad-description">Description: <br><span>{{object.description}}</span></div>
		<div class="ad-price">
			Price: <span>{{object.price}} $</span>
		</div>
		<div class="ad-condition">
			Condition: <span>{{object.item_condition}}</span>
		</div>
		<hr>
		<div class="ad-option">
			{% if object.sold %} {% else %}
			<!-- this should be POST-Ajax request to message center. I think all current messages should be displayed in bottom
POST API endpoint == ~/messages
Format JSON
{
		author = {{user.id}}
    advert = {{object.id}}
    message_text = What this all about
}
-->
<script>
function postAdd() {
	var message_text = $('.write-user').val();
	$.ajax({
			type: "POST",
			url: "{% url 'message_create' %}",
			data: {
        'user_id': {{ object.owner_id }},
        'advert_id': {{ object.id }},
        'message_text': message_text,
        'csrfmiddlewaretoken': '{{ csrf_token }}',
      },
			success : function(json) {
                // hide the post
              $('.write-user').val('');
              $('#chat-user').hide(); // hide the post on success
              alert("ok");
              //output the success popup
            },

      error : function(xhr,errmsg,err) {
                // Show an error
                // $('#results').html("<div class='alert-box alert radius' data-alert>"+
                // "Oops! We have encountered an error. <a href='#' class='close'>&times;</a></div>");

								//output the success popup
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
      }
	});
}
</script>


			<!-- This is something contradictionary. Because David tell me this is not an auction, but he still need this button-->
			<!-- POST Ajax request to POST API endpoint == ~/messages
JSON
{
	author = {{user.id}}
    advert = {{object.id}}
    message_text = "Whant buy this {{object.title}} for {new_price_from_popup_enter_value_whatever}"
}
-->
<script>
function makeOffer() {
	var message_text = "I'd like to purchse" + " '{{object.title}}' " + "for " + $('#ad-price').val() + "$";
	$.ajax({
			type: "POST",
			url: "{% url 'message_create' %}",
			dataType: "json",
			data: {
        "user_id": {{ object.owner_id }},
        "advert_id": {{ object.id }},
        "message_text": message_text,
        'csrfmiddlewaretoken': '{{ csrf_token }}',
      },
			success : function(json) {
                // hide the post
              $('#Makeanoffer').hide(); // hide the post on success
              alert("ok");
              //output the success popup
            },

            error : function(xhr,errmsg,err) {
                // Show an error
                // $('#results').html("<div class='alert-box alert radius' data-alert>"+
                // "Oops! We have encountered an error. <a href='#' class='close'>&times;</a></div>");

								//output the success popup
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
			}
	);
}
</script>
      {% if user != object.owner.user %}
         <button class="btn btn-primary" data-toggle="modal" data-target="#chat-user">Chat</button>
			   <button class="btn btn-success" data-toggle="modal" data-target="#Makeanoffer">Make an offer</button>
			   <button class="btn btn-info" id="purchse">Purchase</button>
      {% endif %}
      {% if user == object.owner.user %}
			   <a href="{% url 'edit-advert' object.id %}"><button class = "btn btn-primary">Update</button></a>
      {% endif %}

      {% endif %}
			<!-- <br> -->
			<!-- <a class = "user-part btn"href="{% url 'user_profile' object.owner.id %}">User part
      <img src="{{ object.owner.avatar_url }}" alt="Meet the {{object.owner}}"></a> -->
		</div>

	</div>
</div>
<div class="popups">
	<!-- //Popup Make an offer -->
	<div id="Makeanoffer" class="modal fade" role="dialog">
		<div class="modal-dialog popup-offer">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Make an offer</h4>
				</div>
				<div class="modal-body">
					<div class="ad_value">
						<div class="input-group price">
							 <input type="numberw" id ="ad-price" class = "ad-input">
							 <div class="input-group-addon">$ </div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn" data-dismiss="modal" onclick="makeOffer()">Offer</button>
				</div>
			</div>

		</div>
	</div>
	<!-- //Popup Make an offer -->

	<!-- Send a message -->
		<div id="chat-user" class="modal fade" role="dialog">
		<div class="modal-dialog popup-offer">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Write a message</h4>
				</div>
				<div class="modal-body">
					<div class="ad_value">
					<textarea name="name" class = "write-user" autofocus>
					</textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn" data-dismiss="modal" onclick="postAdd()">Send</button>
				</div>
			</div>
		</div>
	</div>
	<!-- Send a message -->
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
  $("#purchse").click(function(e) {
    e.preventDefault();
    var message_text = "I'd like to purchse" + " '{{object.title}}'";
    $.ajax({
        type: "POST",
        url: "{% url 'message_create' %}",
        dataType: "json",
        data: {
          "user_id": {{ object.owner_id }},
          "advert_id": {{ object.id }},
          "message_text": message_text,
          'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        success : function(json) {
          alert("ok");
          //output the success popup
        },
        error : function(xhr,errmsg,err) {
            // Show an error
            // $('#results').html("<div class='alert-box alert radius' data-alert>"+
            // "Oops! We have encountered an error. <a href='#' class='close'>&times;</a></div>");

            //output the success popup
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
        }
    );
  })
</script>
{% endblock %}

templates/board/advert_form.html
<div>
	<div>{% extends 'base.html' %} {% block content %}
		<div class="col-sm-offset-2 col-sm-8 add-advert">
			<form class="form-horizontal" action="{% url 'add-advert' %}" method="post" enctype="multipart/form-data">
				{%csrf_token%} {% load widget_tweaks %}
				<h2 class="reg_tittle">Add new advertisement on UNIKO</h2>
				<div class="ad_value">
					<label for=ad-title class="reg_label"><b>Title</b></label>
					<br> {% render_field form.title class+="ad-input ad-input-title" id+="ad-title"%}
				</div>

				<div class="ad_value">
					<label for="ad-desc" class="reg_label"><b>Description</b></label>
					<br> {% render_field form.description class+="ad-input ad-input-desc" id+="ad-desc"%}
				</div>
				<label for="ad-price" class="reg_label">Price</label><br>
				<div class="input-group price">
					<div class="input-group-addon">$ </div>
					 {% render_field form.price class+="ad-input" id+="ad-price"%}

				</div>

				<div class="ad_value">
					<label for="ad-cond" class="reg_label"><b>Condition</b></label>
					<br> {% render_field form.item_condition class+="ad-input" id+="ad-cond"%}
				</div>

				<!-- 		        	        <div class="ad_value">
		            <label for="usr_name" class="reg_label">Hidden</label>{% render_field form.hidden class+="ad-input" id+="usr_name"%}
		        </div> -->
				<div class="ad_value">
					<label for="ad-cat" class="reg_label"><b>Category</b></label>
					<br> {% render_field form.category class+="ad-input" id+="ad-cat"%}
				</div>

				{{ advert_photos.management_form }}
				{{ advert_photos.as_p }}

				<div class="file-drop-area">
					<span class="fake-btn"><b>Choose files</b></span>
					<span class="file-msg js-set-number">or drag and drop files here</span>
					<input type="file" id="files" name="files[]" class="file-input" multiple />
					<output id="list"></output>
				</div>

				<script>
					function handleFileSelect(evt) {
						var files = evt.target.files; // FileList object

						// Loop through the FileList and render image files as thumbnails.
						for (var i = 0, f; f = files[i]; i++) {

							// Only process image files.
							if (!f.type.match('image.*')) {
								continue;
							}

							var reader = new FileReader();

							// Closure to capture the file information.
							reader.onload = (function(theFile) {
								return function(e) {
									// Render thumbnail.
									var span = document.createElement('span');
									span.innerHTML = ['<img class="thumb" src="', e.target.result,
										'" title="', escape(theFile.name), '"/>'
									].join('');
									document.getElementById('list').insertBefore(span, null);
								};
							})(f);

							// Read in the image file as a data URL.
							reader.readAsDataURL(f);
						}
					}

					document.getElementById('files').addEventListener('change', handleFileSelect, false);
				</script>

				<div class="edit-btn">
					<Button type="submit" class="btn btn-primary reg-btn">Submit ad</Button>
				</div>
			</form>
			</form>
		</div>
		{% endblock %}</div>
</div>

templates/board/advert_update.html
{% extends 'base.html' %} {% block content %}
<div>
	<div>
		<div class="col-sm-offset-2 col-sm-8 add-advert">
			<form class="form-horizontal" action="{% url 'edit-advert' object.id %}" method="post" enctype="multipart/form-data">
				{%csrf_token%} {% load widget_tweaks %}
				<h2 class="reg_tittle">Submit your ad on UNIKO</h2>
				<div class="ad_value">
					<label for=ad-title class="reg_label">Title</label>
					<br> {% render_field form.title class+="ad-input ad-input-title" id+="ad-title"%}
				</div>

				<div class="ad_value">
					<label for="ad-desc" class="reg_label">Description</label>
					<br> {% render_field form.description class+="ad-input ad-input-desc" id+="ad-desc"%}
				</div>
				<label for="ad-price" class="reg_label">Price</label><br>
				<div class="input-group price">
			<div class="input-group-addon">$ </div>
					 {% render_field form.price class+="ad-input" id+="ad-price"%}
				</div>

				<div class="ad_value">
					<label for="ad-cond" class="reg_label">Condition</label>
					<br> {% render_field form.item_condition class+="ad-input" id+="ad-cond"%}
				</div>

				<!-- 		        	        <div class="ad_value">
		            <label for="usr_name" class="reg_label">Hidden</label>{% render_field form.hidden class+="ad-input" id+="usr_name"%}
		        </div> -->

				<div class="ad_value">
					<label for="ad-cat" class="reg_label">Category</label>
					<br> {% render_field form.category class+="ad-input" id+="ad-cat"%}
				</div>

				{% comment %}
				{{ advert_photos.management_form }}

				{% for set_element in advert_photos %}
					<img src="set_element.image.url" />
					{{ set_element.image}}
					{{ set_element.delete}}
				{% endfor %}
				{% endcomment %}

				<div class="file-drop-area">
					<span class="fake-btn">Choose files</span>
					<span class="file-msg js-set-number">or drag and drop files here</span>
					<input type="file" id="files" name="files[]" class="file-input" multiple />
					<output id="list">
						{% for advertimage in object.advertimages_set.all %}
							<span><img class="thumb" src="{{ advertimage.image.url }}" title="{{ advertimage.image.name }}"></span>
						{% endfor %}
					</output>
				</div>

				<script>
					function handleFileSelect(evt) {
						var files = evt.target.files; // FileList object

						// Loop through the FileList and render image files as thumbnails.
						for (var i = 0, f; f = files[i]; i++) {

							// Only process image files.
							if (!f.type.match('image.*')) {
								continue;
							}

							var reader = new FileReader();

							// Closure to capture the file information.
							reader.onload = (function(theFile) {
								return function(e) {
									// Render thumbnail.
									var span = document.createElement('span');
									span.innerHTML = ['<img class="thumb" src="', e.target.result,
										'" title="', escape(theFile.name), '"/>'
									].join('');
									document.getElementById('list').insertBefore(span, null);
								};
							})(f);

							// Read in the image file as a data URL.
							reader.readAsDataURL(f);
						}
					}

					document.getElementById('files').addEventListener('change', handleFileSelect, false);
				</script>

				<div class="edit-btn">
					<Button type="submit" class="btn btn-primary reg-btn">Update ad</Button>
				</div>
			</form>
			</form>
		</div>
		{% endblock %}</div>
</div>

templates/board/index.html
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}
{% block content %}
			<div class="main__content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-sm-12 horizontal-filter">
							<a href = "#">
								<i class="" aria-hidden="true"></i>
								<span>All</span>
							</a>
{% for category in categories %}
		<a href="{% url 'advert-list-cats' category.id %}">
			<i class="fa fa-{{category.pictogram}}" aria-hidden="true"></i>
			<span>{{category.name}}</span>
		</a>
{% endfor %}
						</div>
						<div class="col-sm-12">
							<div class="main-container">
								<div role="tabpanel" class="tab-pane active" id="panel-1">
									<div class="row masonry-container">

										<!-- <div class="col-md-3 col-xs-6 item category-filter">
											<div class="thumbnail filter">
												<h3><a href="{% url 'advert-list'%}">Categories</a></h3>
												<ul class = "filter-categories">
												{% for category in categories %}
													<li>
														<a href="{% url 'advert-list-cats' category.id %}">
															<i class="fa fa-{{category.pictogram}}" aria-hidden="true"></i>
															<span>{{category.name}}</span>
														</a>
													</li>
		<li><a href="#"><i class="fa fa-book" aria-hidden="true"></i>Books</a></li>
													<li><a href="#"><i class="fa fa-wrench" aria-hidden="true"></i>Services</a></li>
													<li><a href="#"><i class="fa fa-television" aria-hidden="true"></i>House appliances</a></li>
													<li><a href="#"><i class="fa fa-bed" aria-hidden="true"></i>Furniture</a></li>
													<li><a href="#"><i class="fa fa-male" aria-hidden="true"></i>Clothes</a></li>
 										{% endfor %}
												</ul>
											</div>
										</div><!--/.item  -->

										{% for advert in object_list %}
										<a href="{% url 'advert-detail' advert.id %}">
										<div class="col-md-3 col-xs-6 item">
											<div class="thumbnail order">

												<div class="order-image">
													<img src="{{ advert.main_image }}">
												</div>
												<div class="caption">
													<h4 class = "item_title">{{advert.title}}</h4>
													<span class="item_description">$ {{advert.price}}</span>
												</div>
											</div>
										</div><!--/.item  -->
										</a>
										{% endfor %}

									</div> <!--/.masonry-container  -->
								</div><!--/.tab-panel -->
							</div><!-- /.container -->
						</div>
					</div>
				</div>
			</div>

<!-- 			<div class="join-us">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-12 please-login">
							<p>Create a <span class = "login-uniko">Uniko</span> account and start buying and selling amoungst your peers</p>
							<a href="#signinPopup" class="btn btn-default" data-toggle="modal">JOIN YOUR COMMUNITY</a>
 						</div>
					</div>
				</div>
			</div>
 -->{% endblock %}