adv_board/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from landing import views
from registration.backends.hmac.views import RegistrationView
from users.forms import UnikoRegistrationForm
from users.views import UnikoRegistrationView
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r"^$", views.Homepage.as_view(), name="landing"),
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include("advert_messages.urls")),
    url(r'^users/', include("users.urls")),
    url(r'^board/', include("board.urls")),
    url(r'^accounts/register/$', UnikoRegistrationView.as_view(form_class=UnikoRegistrationForm),
        name='registration:registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls', namespace="registration")),
    url(r'^users/profiles', views.Homepage.as_view(), name="registration_complete"),
    url(r'^users/profiles', views.Homepage.as_view(), name="registration_activation_complete"),
    url(r'^privacy_policy$', TemplateView.as_view(template_name='privacy_policy.html'), name='privacy_policy'),
    url(r'^terms_of_service$', TemplateView.as_view(template_name='terms_of_service.html'), name='terms'),
    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^faq$', TemplateView.as_view(template_name='faq.html'), name='faq'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
# from .views import AdvertViewSet, StakesViewSet
# from rest_framework.routers import DefaultRouter
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.AdvertListView.as_view(), name="advert-list"),
    url(r'^([0-9]+)/$', views.AdvertListView.as_view(), name="advert-list-cats"),
    url(r'^add_advert/$', views.AdvertCreate.as_view(), name="add-advert"),
    url(r'^edit_advert/(?P<pk>[0-9]+)/$',
        views.AdvertUpdate.as_view(), name="edit-advert"),
    url(r'^del_advert/(?P<pk>[0-9]+)/$',
        views.AdvertDelete.as_view(), name="delete-advert"),
    url(r'^advert/(?P<pk>[0-9]+)/$',
        views.AdvertDetail.as_view(), name="advert-detail"),
    url(r"^advert/(?P<pk>[0-9]+)/check_sold/$",
        views.AdvertSoldView.as_view(), name="advert_check_sold"),
    url(r"^advert/(?P<pk>[0-9]+)/sold", views.AdvertSoldUpdate.as_view(), name="advert_sold"),
]


# router = DefaultRouter()
# router.register(r'advert', AdvertViewSet)
# router.register(r'stakes', StakesViewSet)

# urlpatterns = router.urls

users/urls.py
from .views import ReviewViewSet
from rest_framework.routers import DefaultRouter
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/update$',
        views.UserUpdate.as_view(), name="update_profile"),
    url(r'^(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name="user_profile"),

]

router = DefaultRouter()
router.register(r'reviews', ReviewViewSet)
urlpatterns += router.urls

board/models.py
from django.db import models
from users.models import UserProfile
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(_("Category"), max_length=100)
    pictogram = models.CharField(_("Pict"), max_length=50, blank=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name


class AdvertManager(models.Manager):
    def get_queryset(self):
        return super(AdvertManager, self).get_queryset()

    def on_sale(self):
        return super(AdvertManager, self).get_queryset().filter(sold=False, hidden=False)


class Advert(models.Model):

    CONDITIONS = (("used", "Used"), ("like_new", "Like new"), ("new", "New"))

    owner = models.ForeignKey(UserProfile, verbose_name=_("Seller"))
    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(_("Description"))
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(
        _("Price"), max_digits=10, decimal_places=2, default=0)
    item_condition = models.CharField(
        _("Condition"), max_length=8, choices=CONDITIONS, blank=True, null=True)
    sold = models.BooleanField(_("Sold"), default=False)
    sold_to = models.ForeignKey(UserProfile, verbose_name=_(
        "Buyer"), related_name=_("Buyer"), null=True, blank=True)
    hidden = models.BooleanField(_("Hide"), default=False)
    category = models.ForeignKey(Category)

    objects = AdvertManager()

    class Meta:
        verbose_name = _("Advert")
        verbose_name_plural = _("Adverts")
        ordering = ["created_at"]

    def get_absolute_url(self):
        return reverse('advert-detail', kwargs={'pk': self.id})

    @property
    def main_image(self):
        img = AdvertImages.objects.filter(advert=self).first()
        if img:
            return img.image.url
        else:
            return ""  # static No-image-placeholder

    def __str__(self):
        return "{}".format(self.title)


class AdvertImages(models.Model):
    advert = models.ForeignKey(Advert)
    image = models.ImageField(upload_to='adverts')

users/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.db.models import Avg
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings



class Campus(models.Model):
    name = models.CharField(_("Campus name"), max_length=100)

    class Meta:
        verbose_name = _("Campus")
        verbose_name_plural = _("Campuses")

    def __str__(self):
        return self.name


class CampusDomain(models.Model):
    campus = models.ForeignKey(Campus, related_name="emails")
    domain = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if not self.domain.endswith("edu") and not settings.DEBUG:
            return
        super(CampusDomain, self).save(*args, **kwargs)

    def __str__(self):
        return "{}:{}".format(self.campus, self.domain)


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="profile")
    name = models.CharField(_("First name"), max_length=100, blank=True)
    surname = models.CharField(_("Surname"), max_length=100, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    campus = models.ForeignKey(Campus)
    email = models.EmailField()
    description = models.TextField(_("Description"), blank=True)

    def __str__(self):
        return self.user.username

    def new_messages_count(self):
        return self.messages_to_me.filter(was_read=False).count()

    @property
    def average_rating(self):
        rate = Review.objects.filter(user=self).aggregate(Avg('rating')).get("rating_avg", 0.00)
        return rate

    @property
    def media_directory_path(self):
        return '/users/{}'.format(self.user.username)

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        else:
            return static('img/user')


class Review(models.Model):
    user = models.ForeignKey(UserProfile)
    author = models.ForeignKey(UserProfile, related_name="Author")
    rating = models.PositiveSmallIntegerField(_("Rating"))
    text = models.TextField(_("Review"))
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Review")
        verbose_name_plural = _("Reviews")
        ordering = ["created_at"]

    def save(self, *args, **kwargs):
        if not settings.DEBUG:
            if self.user == self.author:
                raise Exception("You can't review yourself")
            if Review.objects.filter(user=self.user, author=self.author).first():
                raise Exception("You already review this user")
        super(Review, self).save(*args, **kwargs)

    def __str__(self):
        return "{} to {}: {}".format(self.author, self.user, self.rating)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created and not instance.is_staff:
        domain = instance.email.split("@")[1]
        searched_domain = CampusDomain.objects.filter(domain=domain).first()
        if searched_domain:
            UserProfile.objects.create(
                user=instance, campus=searched_domain.campus, email=instance.email)

users/forms.py
from registration.forms import RegistrationFormTermsOfService, RegistrationFormUniqueEmail
from django import forms
from .models import CampusDomain, Campus, UserProfile
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class UnikoRegistrationForm(RegistrationFormUniqueEmail, RegistrationFormTermsOfService):
    colledge = forms.ModelChoiceField(queryset=Campus.objects.all())

    def is_valid(self):
        mail = self.data["email"]
        if mail:
            domain = mail.split("@")[1]
            searched_domain = CampusDomain.objects.filter(
                domain=domain).first()
            if not searched_domain:
                self.add_error("email", "Your email not allowed")
                return False
            return True

        return super(UnikoRegistrationForm, self).is_valid()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "tos", "colledge"]


class UserProfileForm(forms.ModelForm):
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        required=False
    )

    class Meta:
        model = UserProfile
        fields = ("name", "surname", "description", "avatar")

users/views.py
from django.views.generic.detail import DetailView
from .models import Review, UserProfile
from django.views.generic.edit import UpdateView
from django.shortcuts import reverse, redirect
from .serializers import ReviewSerializer
from rest_framework import viewsets
from rest_framework.response import Response
from django.core.exceptions import PermissionDenied
from registration.backends.hmac.views import RegistrationView
from django.contrib.auth.models import User
from users.forms import UnikoRegistrationForm, UserProfileForm


class ReviewViewSet(viewsets.ModelViewSet):
    serializer_class = ReviewSerializer
    queryset = Review.objects.all()

    # def list(self, request):
    #     queryset = Review.objects.all()
    #     serializer = ReviewSerializer(queryset, many=True)
    #     return Response(serializer.data)

    def retrieve(self, request, pk):
        queryset = Review.objects.filter(user__id=pk)
        serializer = ReviewSerializer(queryset, many=True)
        return Response(serializer.data)


class UserDetail(DetailView):
    model = UserProfile
    template_name = "users/profile.html"
    fields = "__all__"


class UserUpdate(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "users/update.html"

    def form_valid(self, form):
        if 'password' in form.cleaned_data and form.cleaned_data['password']:
            self.request.user.set_password(form.cleaned_data['password'])
            self.request.user.save()
        return super(UserUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse('user_profile', args=[self.object.id])

    def get_object(self, *args, **kwargs):
        if int(self.kwargs.get("pk", 0)) != self.request.user.profile.id:
            raise PermissionDenied("try to change other's people details, bad boy?")
        else:
            return super(UserUpdate, self).get_object()


class UnikoRegistrationView(RegistrationView):
    form_class = UnikoRegistrationForm

    def register(self, form):
        user = User(username=form.data["username"],
            email=form.data["email"])
        user.set_password(form.data["password1"])
        user.active = False
        user.save()
        # send_mail with rendered template
        return user

templates/users/profile.html
{% extends 'base.html' %} {% load static %} {% load staticfiles %} {% block content %}
<div class="container">
	<div class="profile-header">
		<div class="profile-edit">
			{% if user.profile.id == object.id %}
			<a href="{% url 'update_profile' object.id %}"><i class="fa fa-cog" aria-hidden="true"></i></a> {% endif %}
		</div>
		<div class="profile-name">
			<span>Meet {{object.name}} {{object.surname}}</span>
		</div>
		<div class="profile-avatar">
			{%if object.avatar %}
			<img src={{object.avatar_url}}> {%else%}
			<img src="{% static 'img/user'%}"> {%endif%}

		</div>

		<!-- <div class="profile-rating">
					<span class="stars">{{object.average_rating}}</span>
							<a href="#" data-toggle="modal" data-target="#addReview"><span >({{object.average_rating}})</span></a>
			    </div> -->
		<div class="user-rating">
			<div class="star_rating">{{object.average_rating}}</div>
			<div class="rating-score"><a href="#" data-toggle="modal" data-target="#addReview"><span >({{object.average_rating}})</span></a></div>
		</div>
	</div>
	<div class="profile-description">
		<div class="input-group desc-block pr-desc">
			<div class="input-group-addon">
				About me
			</div>
			<span>{{object.description}}</span>
		</div>
	</div>
	<div class="profile-ad">
		<div class="main__content">
			<div class="container-fluid">
				<div class="row">
					<div class="col-sm-12">
						<div class="main-container">
							<div role="tabpanel" class="tab-pane active" id="panel-1">
								<div class="row masonry-container">


									{% for advert in object.advert_set.all %}
									<a href="{% url 'advert-detail' advert.id %}">
										<div class="col-md-3 col-xs-6 item">
											<div class="thumbnail order">

												<div class="order-image">
													<img src="{{ advert.main_image }}">
												</div>
												<div class="caption">
													<h4 class="item_title">{{advert.title}}</h4>
													<span class="item_description">{{advert.price}} $</span>
												</div>
											</div>
										</div>
										<!--/.item  -->
									</a>
									{% endfor %}

								</div>
								<!--/.masonry-container  -->
							</div>
							<!--/.tab-panel -->
						</div>
						<!-- /.container -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="push"></div>
</div>
<div class="popups">
	<!-- //Popup Make an offer -->
	<div id="addReview" class="modal fade" role="dialog">
		<div class="modal-dialog add-review">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Add review</h4>
				</div>
				<div class="modal-body">
					{% for review in object.review_set.all %}
						<div class="review-body">
							<div class="review-avatar">
								<img src="{{ review.user.avatar_url }}" alt="review-avatar">
							</div>
							<div class="review-content">
								<div class="review-auther">
									{{ review.user }}
								</div>
								<div class="review">
									{{ review.text }}
								</div>
							</div>
							<div class="review-score">
								<div class="star_rating" style="width: 100%">{{ review.rating }}</div>
							</div>
						</div>
					{% endfor %}

				</div>
				<div class="modal-footer">
					<a href="#" class="btn btn-review" data-toggle="modal" data-target="#newReview">Write new review</a>
				</div>
			</div>
		</div>
	</div>
	<!-- //Popup Make an offer -->


	<div id="newReview" class="modal fade" role="dialog">
		<div class="modal-dialog write-review">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Write a review</h4>

					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">
					<!-- RATING - Form -->
					<form class="rating-form2" action="#" method="post" name="rating-movie">
						<textarea name="review" class="write-user"></textarea>

						<div class="form-item">

							<input id="rating-5" name="rating" type="radio" value="5" />
							<label for="rating-5" data-value="5">
	<span class="rating-star">
		<i class="fa fa-star-o"></i>
		<i class="fa fa-star"></i>
	</span>
	<span class="ir">5</span>
</label>
							<input id="rating-4" name="rating" type="radio" value="4" />
							<label for="rating-4" data-value="4">
	<span class="rating-star">
		<i class="fa fa-star-o"></i>
		<i class="fa fa-star"></i>
	</span>
	<span class="ir">4</span>
</label>
							<input id="rating-3" name="rating" type="radio" value="3" />
							<label for="rating-3" data-value="3">
	<span class="rating-star">
		<i class="fa fa-star-o"></i>
		<i class="fa fa-star"></i>
	</span>
	<span class="ir">3</span>
</label>
							<input id="rating-2" name="rating" type="radio" value="2" />
							<label for="rating-2" data-value="2">
	<span class="rating-star">
		<i class="fa fa-star-o"></i>
		<i class="fa fa-star"></i>
	</span>
	<span class="ir">2</span>
</label>
							<input id="rating-1" name="rating" type="radio" value="1" />
							<label for="rating-1" data-value="1">
	<span class="rating-star">
		<i class="fa fa-star-o"></i>
		<i class="fa fa-star"></i>
	</span>
	<span class="ir">1</span>
</label>

						</div>

					</form>


				</div>
				<div class="modal-footer">
					<button id='review-send' type="button" class="btn" data-dismiss="modal">Send</button>
				</div>
			</div>
		</div>
	</div>


<script>
$('#review-send').click(function(e){
	e.preventDefault();
	var $form = $('.rating-form2');
	var text = $form.find('textarea[name="review"]').val();
	var rating = $form.find('input[name="rating"]').val();
	$.ajax({
			type: "POST",
			url: "{% url 'review-list' %}",
			dataType: "json",
			data: {
				'user': {{ object.id }},
				'author': {{ request.user.profile.id }},
				'text': text,
				'rating': rating,
				'csrfmiddlewaretoken': '{{ csrf_token }}',
			},
			success : function(json) {
      	window.location.href = '.'
      },
      error : function(xhr,errmsg,err) {
      	console.log(xhr.status + ": " + xhr.responseText);
      }
	});

});
</script>
{% endblock %}

</div>

templates/users/update.html
{% extends 'base.html' %} {% load static %} {% load staticfiles %} {% block content %}
<div class="col-sm-offset-2 col-sm-8">
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {%csrf_token%} {% load widget_tweaks %}
    <h1 class="reg_tittle">Meet {{object.name}} {{object.surname}}</h1>
  <div class="reg_value">
    <div class="form-group">
          <div class="main-img-preview">
          {% if object.avatar %}
            <img class="thumbnail img-preview" src="{{ object.avatar_url }}" title="Preview Logo">
          {% else %}
            <img class="thumbnail img-preview" src="{% static 'img/user'%}" title="Preview Logo">
          {% endif %}
          </div>
          <div class="input-group">
            <input id="fakeUploadLogo" class="form-control fake-shadow" placeholder="Choose File" disabled="disabled">
            <div class="input-group-btn">
              <div class="fileUpload btn btn-danger fake-shadow">
              <input type="file" class="inputfile" id="{{ form.avatar.id_for_label }}" name="{{ form.avatar.html_name }}" />
              </div>
            </div>
          </div>
        </div>

    </div>
    <div class="input-group">
         <div class="input-group-addon">
           <i class="fa fa fa-user"></i>
         </div>
       {% render_field form.name class+="reg_input" %}
       <div class="input-group-addon">
         <i class="fa fa-user-o"></i>
       </div>
     {% render_field form.surname class+="reg_input"%}
    </div>

    <div class="input-group desc-block pr-desc">
         <div class="input-group-addon">
        About me
         </div>
       {% render_field form.description class+="reg_input"%}
    </div>
    <div class="input-group edit-pass">
         <div class="input-group-addon">
           <i class="fa fa-lock"></i>
         </div>
       {% render_field form.password class+="reg_input" %}
    </div>

<div class="edit-btn">
    <Button type="submit" class="btn btn-primary reg-btn">Update</Button></div>
  </form>
</div>

{% endblock %}